apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.networkPolicy.name }}
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.networkPolicy.backendAppLabel }}
  policyTypes:
    - Ingress
    - Egress

  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ .Values.networkPolicy.frontendAppLabel }}
      ports:
        - protocol: TCP
          port: {{ .Values.networkPolicy.backendPort }}

  egress:
    - to:
        - podSelector:
            matchLabels:
              app: {{ .Values.networkPolicy.databaseAppLabel }}
      ports:
        - protocol: TCP
          port: {{ .Values.networkPolicy.databasePort }}

    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              {{ .Values.networkPolicy.dns.labelKey }}: {{ .Values.networkPolicy.dns.labelValue }}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
