apiVersion: v1
kind: ResourceQuota
metadata:
  name: cloud-ninjas-resource-quota
  namespace: cloud-ninjas   # ← must exist
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "6"
    limits.memory: 10Gi
