apiVersion: v1
kind: ResourceQuota
metadata:
  name: cloud-ninjas-resource-quota
  namespace: cloud-ninjas   # ← must exist
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 3Gi
    limits.cpu: "4"
    limits.memory: 4Gi
